#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

if [ ! -e ./util/build ]; then
  echo "$0 must be run from the top of the project tree"
  exit
fi

git log --oneline -1
[ -d staging ] && rm -r ./staging
mkdir staging
git archive --format=tar HEAD | (cd staging; tar -xf -)
cd staging

version=2.6.0-10
git_version=v2.6.0

# replace with a path to your local clone
giturl=/opt/cmdstan/stan

#tarop=--list
tarop=--extract

rm -rf inst/include/stan
mkdir -p inst/include/stan
git archive --format=tar --remote=$giturl $git_version:src/stan  | (cd inst/include/stan; tar $tarop --file - )

today=$(date +%Y-%m-%d)
rm -f DESCRIPTION
perl -pe "s/VERSION/$version/; s/TODAY/$today/" < DESCRIPTION.in > DESCRIPTION

rm -f StanHeaders*.tar.gz
R CMD build .
mv DESCRIPTION DESCRIPTION.old  # keep it around, but prevent accidental editing
